apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tanka.dev/environment: ef8004c80176691d8a0f3688c077aa401e0b6083174fa72e
  name: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - image: prom/prometheus
        imagePullPolicy: IfNotPresent
        name: prom
        ports:
        - containerPort: 9090
          name: prom
